// prep-fonts.mjs — build the bundled typeface set.
//
// Run by hand, NOT as part of `npm run build`: it needs the network, and its
// output is committed.
//
//   node scripts/prep-fonts.mjs
//
// Concord never fetches a webfont at runtime — asking a font host for a file on
// every launch tells that host your IP and the moment you opened the app. That
// rule is about RUNTIME, though. Shipping the files inside the app is the same
// deal as the bundled Twemoji: local bytes, no request, no third party.
//
// Which is what makes a real type choice possible at all. Restricted to fonts
// already installed on the machine, "pick a font" means system / serif / mono,
// and every option looks like every other one. These are chosen to be
// unmistakable from each other at a glance.
//
// All are SIL Open Font License 1.1. Only the latin and latin-ext subsets are
// kept; the variable axis carries every weight in one file.

import { mkdirSync, writeFileSync, readdirSync, statSync, rmSync } from "node:fs";
import { join } from "node:path";

const OUT = new URL("../public/fonts/", import.meta.url).pathname;

// A modern UA is required, or the CSS API serves legacy TTF instead of woff2.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// id must match the [data-font] value in app.css.
const FONTS = [
  { id: "inter", family: "Inter", axis: "wght@300..700" },
  { id: "grotesk", family: "Space Grotesk", axis: "wght@400..700" },
  { id: "serif", family: "Source Serif 4", axis: "opsz,wght@8..60,400..700" },
  { id: "mono", family: "JetBrains Mono", axis: "wght@400..700" },
  { id: "hyper", family: "Atkinson Hyperlegible", axis: "wght@400;700" },
  { id: "rounded", family: "Nunito", axis: "wght@400..800" },
  { id: "cyber", family: "Chakra Petch", axis: "wght@400;600;700" },
  { id: "comic", family: "Comic Neue", axis: "wght@400;700" },
];

// Only these subsets are kept: everything else is weight the app never renders.
const KEEP = new Set(["latin", "latin-ext"]);

mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) if (f.endsWith(".woff2")) rmSync(join(OUT, f));

const faces = [];
for (const font of FONTS) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(font.family).replace(/%20/g, "+")}:${font.axis}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  // Blocks arrive as "/* subset */ @font-face {...}" — the comment before each
  // one is the only place the subset name appears.
  const blocks = css.split("/*").slice(1);
  let n = 0;
  for (const b of blocks) {
    const subset = b.slice(0, b.indexOf("*/")).trim();
    if (!KEEP.has(subset)) continue;
    const src = b.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    const weight = b.match(/font-weight:\s*([^;]+);/);
    const range = b.match(/unicode-range:\s*([^;]+);/);
    if (!src) continue;
    const file = `${font.id}-${subset}.woff2`;
    const bytes = Buffer.from(await (await fetch(src[1], { headers: { "User-Agent": UA } })).arrayBuffer());
    writeFileSync(join(OUT, file), bytes);
    faces.push(
      `@font-face {\n` +
        `  font-family: "${font.family}";\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${(weight?.[1] || "400").trim()};\n` +
        `  font-display: swap;\n` +
        `  src: url(/fonts/${file}) format("woff2");\n` +
        (range ? `  unicode-range: ${range[1].trim()};\n` : "") +
        `}`,
    );
    n++;
  }
  console.log(`${font.family}: ${n} file(s)`);
}

writeFileSync(
  join(OUT, "fonts.css"),
  `/* Generated by scripts/prep-fonts.mjs — do not edit by hand.\n` +
    `   All faces are SIL Open Font License 1.1 and served from this app's own\n` +
    `   bundle, never from a font host. */\n\n${faces.join("\n\n")}\n`,
);

const bytes = readdirSync(OUT).reduce((n, f) => n + statSync(join(OUT, f)).size, 0);
console.log(`fonts: ${faces.length} faces, ${(bytes / 1024).toFixed(0)} KB`);
