// Zero-dependency test for the drawn card scenes (`npm test` runs it).
//
// A scene is data that becomes SVG on every viewer's screen, so every way it
// can be wrong is silent: nothing throws, the art just isn't there. The five
// checked here are the ones this library can actually get wrong.
//
//   1. The WIRE. A scene id travels in a peer's profile as `effect`, and
//      internal/app/service.go bounds it with validID: 1–32 characters of
//      a-z/0-9/'-'. An id outside that is dropped on save.
//   2. The SHARED NAMESPACE. `effect` resolves against cardfx.js first and
//      cardscenes.js second, so an id defined in both would make one of them
//      unreachable — and which one wins is an ordering detail, not a decision.
//   3. The PAINTER. `cls` names an animation class and `el` names an element;
//      CardSceneNode.svelte knows a fixed set of each, and anything else is a
//      part that never moves or never draws.
//   4. GRADIENTS. An "@name" fill with no matching def paints nothing at all —
//      url(#missing) is transparent, not an error.
//   5. NUMBERS. A NaN coordinate drops the whole element silently. These are
//      generated by ridge()/sine()/bough(), so one bad argument poisons a
//      hundred points at once rather than one.
import { readFileSync } from "node:fs";
import { CARD_SCENES, CARD_SCENE_BY_ID, CARD_SCENE_GROUPS, cardScene } from "./cardscenes.js";
import { CARD_EFFECTS } from "./cardfx.js";

let failures = 0;
const fail = (msg) => {
  console.error("FAIL:", msg);
  failures++;
};
const ok = (cond, msg) => {
  if (!cond) fail(msg);
};

// The painter is the authority on what exists, not a list kept in step by hand.
const painter = readFileSync(new URL("../CardSceneNode.svelte", import.meta.url), "utf8");
const animClasses = new Set(
  [...painter.matchAll(/^\s{2}\.([a-z][a-z0-9-]*)[\s,{]/gm)].map((m) => m[1]),
);
// "path" is the painter's {:else} fallback, which is precisely why a typo in
// `el` is silent: an unrecognised kind lands there and draws <path d={undefined}>.
const ELEMENTS = new Set([...painter.matchAll(/node\.el === "([a-z]+)"/g)].map((m) => m[1]));
ELEMENTS.add("path");
ok(animClasses.size > 5, "could not read animation classes out of CardSceneNode.svelte");
ok(ELEMENTS.size > 2, "could not read element kinds out of CardSceneNode.svelte");

ok(CARD_SCENES.length >= 10, `expected at least 10 scenes, got ${CARD_SCENES.length}`);

// 2. one id space, two libraries
const fxIds = new Set(CARD_EFFECTS.map((e) => e.id));
const seen = new Set();
let total = 0;

for (const s of CARD_SCENES) {
  const where = s.id || "(no id)";

  // 1. the wire
  ok(/^[a-z0-9-]{1,32}$/.test(s.id || ""), `${where}: id must match validID in service.go`);
  ok(!seen.has(s.id), `${where}: duplicate id`);
  seen.add(s.id);
  ok(!fxIds.has(s.id), `${where}: also a particle effect id — one of the two is unreachable`);
  ok(!!s.name && !!s.group, `${where}: needs a name and a group`);
  ok(Array.isArray(s.parts) && s.parts.length > 0, `${where}: no parts`);

  const defIds = new Set((s.defs || []).map((d) => d.id));
  let animated = 0;

  const walk = (parts, path) => {
    for (const [i, p] of parts.entries()) {
      const at = `${where}${path}[${i}]`;
      total++;

      // 3. the painter
      ok(ELEMENTS.has(p.el), `${at}: element "${p.el}" is not drawn by CardSceneNode.svelte`);
      if (p.cls) {
        for (const c of String(p.cls).split(/\s+/).filter(Boolean)) {
          ok(animClasses.has(c), `${at}: animation "${c}" is not defined in CardSceneNode.svelte`);
        }
        animated++;
      }

      // 4. gradients and filters
      for (const v of [p.fill, p.stroke, p.filter]) {
        if (v == null || v === "none") continue;
        if (String(v)[0] === "@") {
          ok(defIds.has(String(v).slice(1)), `${at}: "${v}" has no matching entry in defs`);
        }
      }

      // 5. numbers. Every geometry field, plus every number inside path data.
      for (const k of ["x", "y", "w", "h", "cx", "cy", "r", "rx", "ry", "sw", "tx", "ty", "x0", "x1", "amp", "dur", "dl", "sc", "a"]) {
        if (p[k] == null) continue;
        ok(Number.isFinite(p[k]), `${at}: ${k} is ${p[k]}`);
      }
      if (p.d != null) {
        ok(typeof p.d === "string" && p.d.length > 0, `${at}: empty path data`);
        ok(!/NaN|undefined|Infinity/.test(p.d), `${at}: path data contains NaN/undefined/Infinity`);
      }
      if (p.a != null) ok(p.a > 0 && p.a <= 1, `${at}: opacity ${p.a} is outside (0,1]`);
      ok(p.el !== "g" || Array.isArray(p.children), `${at}: a group with no children draws nothing`);

      if (p.children) walk(p.children, `${path}[${i}]`);
    }
  };
  walk(s.parts, "");

  ok(animated > 0, `${where}: nothing moves — the library's whole premise is motion`);
  for (const d of s.defs || []) {
    ok(/^[a-z0-9-]+$/.test(d.id), `${where}: def id "${d.id}" should be plain lowercase`);
    ok(
      d.t === "blur" || (Array.isArray(d.stops) && d.stops.length >= 2),
      `${where}: gradient "${d.id}" needs at least two stops`,
    );
  }
}

// Lookup fails closed — the property that makes it safe to paint an id that
// arrived on someone else's broadcast profile.
ok(cardScene("") === null, "cardScene('') should be null");
ok(cardScene("no-such-scene") === null, "an unknown id must resolve to null");
ok(cardScene(CARD_SCENES[0].id) === CARD_SCENES[0], "a known id must resolve to its scene");
ok(Object.keys(CARD_SCENE_BY_ID).length === CARD_SCENES.length, "index size mismatch");
ok(
  CARD_SCENE_GROUPS.reduce((n, g) => n + g.ids.length, 0) === CARD_SCENES.length,
  "every scene must appear in exactly one group",
);

if (failures) {
  console.error(`cardscenes.js: ${failures} failure(s)`);
  process.exit(1);
}
console.log(`cardscenes.js: all passed (${CARD_SCENES.length} scenes, ${total} parts)`);
